### ISSUE TITLE
Crash just after startup

### ISSUE THREAD

**Issue by DevCeo** [Laim/Snap2HTML#5]
Hello just some issue on app:
Crash just after startup and then resume, 

OS: Windows 11
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Net Framework Setup\NDP\v4\Full
    CBS    REG_DWORD    0x1
    Install    REG_DWORD    0x1
    InstallPath    REG_SZ    C:\Windows\Microsoft.NET\Framework64\v4.0.30319\
    Release    REG_DWORD    0x82348
    Servicing    REG_DWORD    0x0
    TargetVersion    REG_SZ    4.0.0
    Version    REG_SZ    4.8.09032

Error Message:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Snap2HTMLNG.Shared.Settings.XmlConfigurator.Read(String node, String rootNode)
   at Snap2HTMLNG.Shared.Updater.Updater..ctor()
   at Snap2HTMLNG.frmMain.frmMain_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Thanks

**Comment by Laim** [comment]
Sorry for delay.  I've had someone else report this to me as well, I'm pretty sure I've forgotten to have a usersettings file create lol.

Will push out a fix shortly.

**Comment by Laim** [comment]
Should be fixed in v3.1: https://github.com/Laim/Snap2HTML-NG/releases/tag/3.1
